libs.tech: klayout: tech: scripts: sealring: Rename input internally
input is a Python build-in function. That means it can never
generate a NameError. See

>>> print(input)
<built-in function input>
>>> print(width)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'width' is not defined

Remove the try-catch block for input since it's dead code and rename
"input" internally to input_file.

This patch doesn't change the external script arguments and doesn't
break any external users.

Signed-off-by: Daniel Schultz <dnltz@aesc-silicon.de>